
import { useEffect, useState, type FormEvent } from "react";
import { motion } from "framer-motion";
import axios from "axios";

import {
  createEvent,
  getEvents,
} from "../../api/event.api";

import type { Event } from "../../types/event";

const Events = () => {
  const [events, setEvents] = useState<Event[]>([]);

  const [type, setType] = useState("");
  const [payload, setPayload] = useState(
    `{
  "paymentId": "pay_123",
  "amount": 4999,
  "currency": "INR"
}`,
  );

  const [showForm, setShowForm] = useState(false);
  const [loading, setLoading] = useState(true);
  const [creating, setCreating] = useState(false);

  const [error, setError] = useState("");
  const [success, setSuccess] = useState("");
  const [apiKey, setApiKey] = useState("");

  const loadEvents = async () => {
    try {
      setError("");

      const response = await getEvents();

      setEvents(response.data);
    } catch (error) {
      if (axios.isAxiosError(error)) {
        setError(
          error.response?.data?.message ||
            "Unable to load events.",
        );
      } else {
        setError("Unable to load events.");
      }
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    loadEvents();
  }, []);

  const handleSubmit = async (
    event: FormEvent<HTMLFormElement>,
  ): Promise<void> => {
    event.preventDefault();

    setError("");
    setSuccess("");

    let parsedPayload: Record<string, unknown>;

    try {
      parsedPayload = JSON.parse(payload);
    } catch {
      setError("Payload must contain valid JSON.");
      return;
    }

    setCreating(true);

    try {
      const response = await createEvent({
        type,
        payload: parsedPayload,
      },
      apiKey,
    );

      setEvents((currentEvents) => [
        response.data,
        ...currentEvents,
      ]);

      setType("");

      setPayload(`{
  "paymentId": "pay_123",
  "amount": 4999,
  "currency": "INR"
}`);

      setShowForm(false);
      setSuccess("Event created successfully.");
    } catch (error) {
      if (axios.isAxiosError(error)) {
        setError(
          error.response?.data?.message ||
            "Unable to create event.",
        );
      } else {
        setError("Unable to create event.");
      }
    } finally {
      setCreating(false);
    }
  };

  return (
    <div className="mx-auto max-w-6xl">

      {/* Header */}
      <div className="mb-8 flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between">
        <div>
          <p className="mb-2 font-mono text-xs uppercase tracking-wider text-blue-400">
            Event stream
          </p>

          <h1 className="text-3xl font-semibold tracking-tight text-white">
            Events
          </h1>

          <p className="mt-2 max-w-2xl text-sm leading-6 text-zinc-400">
            Publish and monitor events generated by your workspace.
          </p>
        </div>

        <motion.button
          whileHover={{ scale: 1.02 }}
          whileTap={{ scale: 0.98 }}
          onClick={() => {
            setShowForm((value) => !value);
            setError("");
            setSuccess("");
          }}
          className="rounded-xl bg-white px-4 py-2.5 text-sm font-semibold text-zinc-950 transition hover:bg-zinc-200"
        >
          {showForm ? "Close" : "+ Create event"}
        </motion.button>
      </div>

      {/* Create event */}
      {showForm && (
        <motion.div
          initial={{ opacity: 0, y: -10 }}
          animate={{ opacity: 1, y: 0 }}
          className="mb-8 rounded-2xl border border-zinc-800 bg-zinc-900/50 p-6 shadow-xl shadow-black/10"
        >
          <div className="mb-6">
            <h2 className="text-lg font-semibold text-white">
              Create event
            </h2>

            <p className="mt-1 text-sm text-zinc-500">
              Publish an event to your TenantRelay workspace.
            </p>
          </div>

          <form
            onSubmit={handleSubmit}
            className="space-y-5"
          >
            <div>
  <label
    htmlFor="api-key"
    className="mb-2 block text-sm font-medium text-zinc-300"
  >
    API Key
  </label>

  <input
    id="api-key"
    type="password"
    value={apiKey}
    onChange={(event) => setApiKey(event.target.value)}
    placeholder="Enter your TenantRelay API key"
    required
    className="w-full rounded-xl border border-zinc-800 bg-zinc-950 px-4 py-3 font-mono text-sm text-white outline-none transition placeholder:text-zinc-600 focus:border-blue-500/60 focus:ring-2 focus:ring-blue-500/10"
  />
</div>
            {/* Event type */}
            <div>
              <label
                htmlFor="event-type"
                className="mb-2 block text-sm font-medium text-zinc-300"
              >
                Event type
              </label>

              <input
                id="event-type"
                type="text"
                value={type}
                onChange={(event) =>
                  setType(event.target.value)
                }
                placeholder="payment.created"
                required
                className="w-full rounded-xl border border-zinc-800 bg-zinc-950 px-4 py-3 font-mono text-sm text-white outline-none transition placeholder:text-zinc-600 focus:border-blue-500/60 focus:ring-2 focus:ring-blue-500/10"
              />
            </div>

            {/* Payload */}
            <div>
              <div className="mb-2 flex items-center justify-between">
                <label
                  htmlFor="event-payload"
                  className="block text-sm font-medium text-zinc-300"
                >
                  Payload
                </label>

                <span className="font-mono text-xs text-zinc-600">
                  JSON
                </span>
              </div>

              <textarea
                id="event-payload"
                value={payload}
                onChange={(event) =>
                  setPayload(event.target.value)
                }
                rows={9}
                spellCheck={false}
                className="w-full resize-y rounded-xl border border-zinc-800 bg-zinc-950 px-4 py-3 font-mono text-sm leading-6 text-zinc-300 outline-none transition placeholder:text-zinc-600 focus:border-blue-500/60 focus:ring-2 focus:ring-blue-500/10"
              />
            </div>

            {/* Error */}
            {error && (
              <motion.div
                initial={{ opacity: 0, y: -5 }}
                animate={{ opacity: 1, y: 0 }}
                className="rounded-xl border border-red-500/20 bg-red-500/10 px-4 py-3 text-sm text-red-400"
              >
                {error}
              </motion.div>
            )}

            <div className="flex justify-end gap-3">
              <button
                type="button"
                onClick={() => setShowForm(false)}
                className="rounded-xl border border-zinc-800 px-4 py-2.5 text-sm font-medium text-zinc-400 transition hover:bg-zinc-900 hover:text-white"
              >
                Cancel
              </button>

              <motion.button
                type="submit"
                disabled={creating}
                whileHover={{
                  scale: creating ? 1 : 1.01,
                }}
                whileTap={{
                  scale: creating ? 1 : 0.98,
                }}
                className="rounded-xl bg-white px-5 py-2.5 text-sm font-semibold text-zinc-950 transition hover:bg-zinc-200 disabled:cursor-not-allowed disabled:opacity-60"
              >
                {creating
                  ? "Publishing..."
                  : "Publish event"}
              </motion.button>
            </div>
          </form>
        </motion.div>
      )}

      {/* Success */}
      {success && (
        <motion.div
          initial={{ opacity: 0, y: -5 }}
          animate={{ opacity: 1, y: 0 }}
          className="mb-6 rounded-xl border border-emerald-500/20 bg-emerald-500/5 px-4 py-3 text-sm text-emerald-400"
        >
          {success}
        </motion.div>
      )}

      {/* Error */}
      {!showForm && error && (
        <div className="mb-6 rounded-xl border border-red-500/20 bg-red-500/10 px-4 py-3 text-sm text-red-400">
          {error}
        </div>
      )}

      {/* Events */}
      <div className="overflow-hidden rounded-2xl border border-zinc-800 bg-zinc-900/30">

        {/* Table header */}
        <div className="hidden grid-cols-[1fr_2fr_160px] border-b border-zinc-800 px-6 py-3 text-xs font-medium uppercase tracking-wider text-zinc-600 md:grid">
          <span>Event type</span>
          <span>Payload</span>
          <span>Created</span>
        </div>

        {loading ? (
          <div className="space-y-3 p-6">
            {[1, 2, 3].map((item) => (
              <div
                key={item}
                className="h-16 animate-pulse rounded-xl bg-zinc-900"
              />
            ))}
          </div>
        ) : events.length === 0 ? (
          <div className="px-6 py-16 text-center">
            <div className="mx-auto mb-4 flex h-12 w-12 items-center justify-center rounded-xl border border-zinc-800 bg-zinc-900">
              <span className="font-mono text-lg text-zinc-600">
                {"{}"}
              </span>
            </div>

            <h3 className="text-sm font-semibold text-white">
              No events yet
            </h3>

            <p className="mt-1 text-sm text-zinc-500">
              Create your first event to start building your event stream.
            </p>
          </div>
        ) : (
          <div className="divide-y divide-zinc-800">
            {events.map((event) => (
              <motion.div
                key={event.id}
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                className="grid gap-4 px-6 py-5 transition hover:bg-zinc-900/60 md:grid-cols-[1fr_2fr_160px] md:items-center"
              >
                {/* Type */}
                <div>
                  <p className="font-mono text-sm text-blue-400">
                    {event.type}
                  </p>

                  <p className="mt-1 font-mono text-[11px] text-zinc-600">
                    {event.id}
                  </p>
                </div>

                {/* Payload */}
                <div className="overflow-hidden rounded-lg border border-zinc-800 bg-zinc-950 px-3 py-2">
                  <pre className="max-h-20 overflow-hidden whitespace-pre-wrap break-all font-mono text-xs leading-5 text-zinc-500">
                    {JSON.stringify(event.payload, null, 2)}
                  </pre>
                </div>

                {/* Created */}
                <div className="text-sm text-zinc-500">
                  {new Date(
                    event.createdAt,
                  ).toLocaleString()}
                </div>
              </motion.div>
            ))}
          </div>
        )}
      </div>
    </div>
  );
};

export default Events;

